apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-deployment
  namespace: lab4
  labels:
    app: lab4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab4
  template:
    metadata:
      labels:
        app: lab4
    spec:
      containers:
        - name: lab4
          image: neaja/min-lab4-image
          imagePullPolicy: IfNotPresent
